name: places
version: 1.0.0+1
description: A new Flutter project.
repository: https://github.com/glin94/surf-flutter-course-giniyatov

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Italic.ttf
          style: italic
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
