name: places
version: 1.0.0+1
description: A new Flutter project.
repository: https://github.com/glin94/surf-flutter-course-giniyatov

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.0
  equatable: ^1.2.6
  flutter_bloc: ^6.1.2
  flutter_mobx: ^1.1.0+2
  flutter_svg: ^0.19.1
  intl: ^0.16.1
  mobx: ^1.2.1+4
  provider: ^4.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - res/assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Italic.ttf
          style: italic
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
